.TH "RSSTAIL" "1" "0.1" "" "User Commands"
.SH "NAME"
rsstail \- a console RSS reader that monitors feeds and outputs new entries
.SH "SYNOPSIS"
.PP 
\fBrsstail\fR [\fBOPTIONS\fB]... \fB\-u\fB URL 
.SH "DESCRIPTION"
.PP 
This manual page was written for the \fBDebian\fP distribution 
because the original program does not have a manual page. 
.PP 

rsstail fetches RSS feeds from specified URLs and outputs them continuously, 
much like \fBtail -f\fB does with files.
.SH "OPTIONS"
.PP 
Options can be given in any order. Options that don't have an argument can be 
combined after a single dash.
 
.IP "\fB\-t\fP" 10
Show a timestamp of when the item was processed
.IP "\fB\-l\fP" 10
Show item's link
.IP "\fB\-e\fP" 10
Show item's enclosure URL
.IP "\fB\-d\fB" 10
Show item's description
.IP "\fB\-p\fB" 10
Show item's publication date
.IP "\fB\-a\fB" 10
Show item's author
.IP "\fB\-c\fB" 10
Show item's comments
.IP "\fB\-g\fB" 10
Show item's GUID
.IP "\fB\-N\fB" 10
Do not show headings
.IP "\fB\-b X\fB" 10
Limit description and comments to \fBX\fB bytes
.IP "\fB\-z\fB" 10
Continue even if there are XML parser errors in the RSS 
feed
.IP "\fB\-Z string\fB" 10
Output user-specified string before all the other headings
.IP "\fB\-n X\fB" 10
Initially show only first \fBX\fB items
.IP "\fB\-H\fB" 10
Strip HTML tags
.IP "\fB\-A username:password\fB" 10
Authenticate against webserver
.IP "\fB\-u URL\fB" 10
URL of RSS feed to tail
.IP "\fB\-i seconds\fB" 10
Check interval in seconds (default is 15 minutes)
.IP "\fB\-r\fB"
Print items in reverse order
.IP "\fB\-x host[:port]\fB" 10
Proxy server to use
.IP "\fB\-y username:password\fB" 10
Credentials for the proxy server
.IP "\fB\-P\fB" 10
Do not exit when an error occurs
.IP "\fB\-1\fB" 10
One shot mode: check the feeds for new items, print them out and exit
.IP "\fB\-v\fB" 10
Be verbose (repeat to increase verbosity)
.IP "\fB\-h\fP" 10 
Show options and their descriptions
.IP "\fB\-V\fP" 10 
Show version of the program
.SH "AUTHOR"
.PP 
This manual page was written by Rene Mayorga <rmayorga@debian.org.sv> for 
the \fBDebian\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 or any later version 
published by the Free Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common\-licenses/GPL. 
